name: example
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  firebase_core: ^1.0.0 # https://pub.dev/packages/firebase_core
  cloud_firestore: ^2.0.0 # https://pub.dev/packages/cloud_firestore
  firebase_auth: ^3.0.0 # https://pub.dev/packages/firebase_auth
  easy_firestore:
    path: ../
    # git:
    #   url: https://github.com/robmllze/easy_firestore.git
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true

