name: example
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.13.4 <3.0.0"
dependencies:
  firebase_core: ^1.6.0 
  cloud_firestore: ^2.5.1 # https://pub.dev/packages/cloud_firestore
  firebase_auth: ^3.1.0 # https://pub.dev/packages/firebase_auth
  easy_firestore:
    path: ../
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true

